version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      upload-download-artifact:
        patterns:
          - 'actions/upload-artifact'
          - 'actions/download-artifact'
